---
title: 'Technique demo'
output: html_document
---

```{r}
rm(list = ls())
int <- F
noise <- F
noise_pred <- F
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, rms, caret, gridExtra, stringr, partykit)
source("sim.R")
source("q-functs.R")
source("sim-test.R")
source("results-functs.R")
```

```{r sim}
set.seed(20161116)
N = 100
dat <- tibble(
  ID = 1:N,
  month = rep(0, N),
  tumor_mass = rep(1, each = N),
  toxicity = rep(1, each = N),
  dose = runif(N, min = 0, max = 1),
  dead = rep(F, N)
)

dat <- genIntNoise(dat, int, noise)

dat <- Mnext(dat, int, noise_pred)
dat <- Wnext(dat, int, noise_pred)
dat <- lamNext(dat, int, noise_pred)
dat <- dat %>% mutate(
  d_next = runif(nrow(.), min = 0, max = 1),
  surv_time = rexp(nrow(.), lam),
  expected_surv = 1/lam,
  dead = ifelse(dead,
                T,
                surv_time < 1)
)

ggplot(dat, aes(x = dose, y = M_next)) + geom_point() +
  geom_smooth(method = "loess")

sum(dat$surv_time < 1)
sum(log(dat$surv_time) < 0)
```

```{r formula}
dat <- sim() %>% filter(month == 0)
form <- M_next ~ dose + tumor_mass + toxicity
numpreds <- 0
```

# rpart
```{r}
set.seed(20170128)
# grid <- expand.grid(cp = 10^(seq(-4, -3, 1)))
mod_rpart <- train(
  form,
  data = dat,
  method = 'rpart1SE',
  minbucket = 2
)
mod <- mod_rpart

ggplot(dat, aes(x = dose, y = M_next)) +
  geom_point() +
  geom_abline(slope = -1.2, intercept = 1.75) +
  geom_point(aes(x = dose, y = predict(mod)), color = "red") +
  geom_line(aes(x = dose, y = predict(mod)), color = "red")

mod$finalModel %>% plotmo()
as.party(mod$finalModel) %>% plot()
as.party(mod$finalModel)
```

# MARS
```{r}
set.seed(20170128)
mod_mars <- train(
  form,
  data = dat,
  method = 'gcvEarth',
  trControl = trainControl(method = "none"),
  tuneGrid = expand.grid(degree = 2)
)
mod <- mod_mars

ggplot(dat, aes(x = dose, y = M_next)) +
  geom_point() +
  geom_abline(slope = -1.2, intercept = 1.75) +
  # geom_point(aes(x = dose, y = predict(mod)), color = "red") +
  geom_line(aes(x = dose, y = predict(mod)), color = "red")

mod$finalModel %>% summary()
mod$finalModel %>% plotmo()
```

# rf
```{r}
set.seed(20170128)
mod_rf <- train(
  form,
  data = dat,
  method = 'ranger',
  tuneGrid = expand.grid(mtry = 1),
  trControl = trainControl(method = "none"),
  min.node.size = 5,
  num.trees = 500
)

mod <- mod_rf

ggplot(dat, aes(x = dose, y = M_next)) +
  geom_point() +
  geom_abline(slope = -1.2, intercept = 1.75) +
  # geom_point(aes(x = dose, y = predict(mod)), color = "red") +
  geom_line(aes(x = dose, y = predict(mod)), color = "red")

mod$finalModel %>% plotmo()
```
