---
title: 'Technique demo'
output: html_document
---

```{r}
# rm(list = ls())
int <- F
noise <- F
noise_pred <- F
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, rms, caret, gridExtra, stringr, partykit)
source("sim.R")
source("sim-test.R")
source("q-functs.R")
source("results-functs.R")
```


```{r formula}
set.seed(20170410)
N = 50
dat <- tibble(
    ID = 1:N,
    month = rep(0, N),
    tumor_mass = runif(N, min = 1, max = 2),
    toxicity = 1,
    dose = runif(N, min = 0, max = 1),
    dead = rep(F, N)
)
  
dat <- genIntNoise(dat, int, noise, noise_pred)
  
dat <- simMonth(dat) %>% rename(
  M = tumor_mass, D = dose, W = toxicity
) %>% mutate(
  Y = M_next - M
)

N = 50
dat_test <- tibble(
    ID = 1:N,
    month = rep(0, N),
    tumor_mass = runif(N, min = 1, max = 2),
    toxicity = 1,
    dose = runif(N, min = 0, max = 1),
    dead = rep(F, N)
)
  
dat_test <- genIntNoise(dat_test, int, noise, noise_pred)
  
dat_test <- simMonth(dat_test) %>% rename(
  M = tumor_mass, D = dose, W = toxicity
) %>% mutate(
  Y = M_next - M
)
```


```{r}
form <- Y ~ D 
numpreds <- 0
```

# rpart
```{r}
set.seed(20170128)
# grid <- expand.grid(cp = 10^(seq(-4, -3, 1)))
mod_rpart <- train(
  form,
  data = dat,
  method = 'rpart1SE',
  minbucket = 5
)
mod <- mod_rpart

ggplot(dat, aes(x = D, y = Y)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = -1.2, intercept = 0.75, linetype = 3) +
  geom_point(aes(x = D, y = predict(mod)), shape = 4) +
  geom_line(aes(x = D, y = predict(mod)), linetype = 1)

ggsave(filename = "ex-plot-cart.png", width = 6, height = 3.5)

# mod$finalModel %>% plotmo()
png(filename = "ex-tree-cart.png", width = 6, height = 3.5, units = "in", res = 300, pointsize = 10)
as.party(mod$finalModel) %>% plot()
dev.off()
as.party(mod$finalModel)

postResample(pred = predict(mod, dat_test), obs = dat_test$Y)
```

# MARS
```{r}
set.seed(20170128)
mod_mars <- train(
  Y ~ D,
  data = dat,
  method = 'gcvEarth',
  trControl = trainControl(method = "none"),
  tuneGrid = expand.grid(degree = 2)
)
mod <- mod_mars

ggplot(dat, aes(x = D, y = Y)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = -1.2, intercept = 0.75, linetype = 3) +
  geom_point(aes(x = D, y = predict(mod)), shape = 4) +
  geom_line(aes(x = D, y = predict(mod)), linetype = 1)

ggsave(filename = "ex-plot-mars.png", width = 6, height = 3.5)

mod$finalModel %>% summary()
plotmo(mod$finalModel)

postResample(pred = predict(mod, dat_test), obs = dat_test$Y)
```

# rf
```{r}
set.seed(20170128)
mod_rf <- train(
  form,
  data = dat,
  method = 'ranger',
  tuneGrid = expand.grid(mtry = 1),
  trControl = trainControl(method = "none"),
  min.node.size = 5,
  num.trees = 100
)

mod <- mod_rf

ggplot(dat, aes(x = D, y = Y)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = -1.2, intercept = 0.75, linetype = 3) +
  geom_point(aes(x = D, y = predict(mod)), shape = 4) +
  geom_line(aes(x = D, y = predict(mod)), linetype = 1)

ggsave(filename = "ex-plot-rf.png", width = 6, height = 3.5)

postResample(pred = predict(mod, dat_test), obs = dat_test$Y)
```
