---
title: "Results"
output: html_document
---

```{r}
rm(list = ls())
library(pacman)
p_load(tidyverse, Hmisc, Gmisc, stringr)
source("sim.R")
source("sim-test-deter.R")
source("q-functs.R")
source("results-functs.R")
```

```{r}
save_all <- F
x <- list(orig = rep(F, 3),
          noise = c(F, T, F),
          noise_pred = c(F, T, T),
          int = c(T, F, F),
          int_noise = c(T, T, F),
          int_noise_pred = rep(T, 3))
```

```{r reward-table}
grp_nms <- c(
  "greedy", "bmars", "mars", "rf", "CART", '1on1off',
  seq(from = 1, to = 0.1, by = -0.1) %>% as.character()
)

grp_labs <- c(
  "best", "BMARS", "MARS", "RF", "CART", '1on1off',
  seq(from = 1, to = 0.1, by = -0.1) %>% as.character()
)

describeM <- function(...) {
  describeMean(..., html = F, plusmin_str = "")
}

for (i in seq_along(x)) {
  int = x[[i]][1]
  noise = x[[i]][2]
  noise_pred = x[[i]][3]
  type_nm <- paste0(
    ifelse(int, "int", ""),
    ifelse(int & noise, "_", ""),
    ifelse(noise, "noise", ""),
    ifelse(noise_pred, "_pred", ""),
    ifelse(!noise_pred & !noise & !int, "orig", "")
  )
  load(paste0(type_nm, "_3.Rdata"))
  prefix <- c("dat_test_", "Q_list_")
  var_nms <- map(prefix, ~ paste0(.x, type_nm)) %>%
    set_names(c("dat_test", "Q_list"))
  dat <- var_nms$dat_test %>% parse(text = .) %>% eval()
  
  if (save_all) {
    if (!int & !noise & !noise_pred) {
      dat_all <- dat %>% mutate(scenario = type_nm)
    } else {
      dat_all <- bind_rows(dat_all, dat %>% mutate(scenario = type_nm))
    }
    rm(list = var_nms %>% flatten_chr())
  }  
  
  r1 <- dat  %>%
    group_by(group) %>% mutate(mod = str_extract(group, "^[a-zA-Z]+|^\\d\\.\\d|^1$|^1on1off")) %>%
    group_by(mod) %>%
    summarise(tot_reward = mean(tot_reward) %>% exp()) %>% ungroup() %>%
    rename_(.dots = setNames("tot_reward", type_nm)) %>%
    mutate(mod = mod %>% factor(levels = grp_nms, labels = grp_labs)) %>%
    arrange(mod)

  # r1 <- getDescriptionStatsBy(exp(dt$tot_reward), by = dt$mod,
  #                              continuous_fn = describeM) %>% t()
  # colnames(r1) <- type_nm
  
  if (i > 1) {
    r_tab <- full_join(r_tab, r1)
  } else {
    r_tab <- r1
  }
}
# labs <- c("Regime", "Basic", "Interaction", "Noise", "Predictive noise", "Interaction + noise", "Interaction + predictive noise")
if (save_all) {
  dat_all <- dat_all %>% filter(scenario == "int", group == "greedy") %>%
    mutate(scenario = "int_noise") %>% bind_rows(dat_all)
  dat_all <- dat_all %>% filter(scenario == "orig", group == "greedy") %>%
    mutate(scenario = "noise") %>% bind_rows(dat_all)
  save(dat_all, file = "all.Rdata")
}

labs <- c("Regime", "B", "N", "PN", "I", "I + N", "I + PN")

rt <- r_tab %>% format.df(dec = 1)

rt <- r_tab

r_tab[1, 2] <- r_tab[1, 3]
r_tab[1, 6] <- r_tab[1, 5]

latex(r_tab, file = "", rowname = NULL, colheads = labs, booktabs = T)
```

```{r, eval = F}
labs_lng <- c("Basic", "Noise", "Predictive noise", "Interaction", "Interaction + noise", "Interaction + predictive noise")
labs_lng <- paste(labs_lng, "scenario")
labs <- c("orig", "noise", "noise_pred", "int", "int_noise", "int_noise_pred")

dat_all <- dat_all %>% group_by(group) %>% mutate(
      # rep = 1:n() %/% (200 * 6 + 1),
      mod = str_extract(group,"^[a-zA-Z]+|^\\d\\.\\d|^1$|^1on1off") %>%
        factor(levels = grp_nms, labels = grp_labs),
      samp = ifelse(str_detect(group, "^[a-zA-Z]+\\d+$"),
                    str_extract(group, "\\d+$"), "0"))

dat_test_all_summ <- dat_all %>% group_by(mod, samp, scenario) %>%
  summarise(mean_reward = mean(tot_reward)) %>% ungroup() %>%
  mutate(scenario = factor(scenario, levels = labs, labels = labs_lng))
```

```{r}
no_int_plot <- ggplot(data = dat_test_all_summ %>%
                        filter(scenario %in% labs_lng[1:3])) +
  geom_boxplot(mapping = aes(x = mod,
                             y = exp(mean_reward))) +
    labs(y = "Mean months of survival",
         x = "Regime") + 
    theme(legend.position = "none") + coord_trans(y = "log") +
  facet_wrap(~ scenario, nrow = 3) + theme_bw()

ggsave(
  file = paste0("results-plot-no-int.png"),
  plot = no_int_plot,
  width = 7.5,
  height = 7
)

int_plot <- ggplot(data = dat_test_all_summ %>% filter(scenario %in% labs_lng[4:6])) +
  geom_boxplot(mapping = aes(x = mod,
                             y = exp(mean_reward))) +
    labs(y = "Mean months of survival",
         x = "Regime") + 
    theme(legend.position = "none") + coord_trans(y = "log") +
  facet_wrap(~ scenario, nrow = 3) + theme_bw()

ggsave(
  paste0("results-plot-int.png"),
  plot = int_plot,
  width = 7.5,
  height = 7
)
```

```{r, eval = F}
dat_summ <- dat_all %>%
  group_by(mod, scenario, ID) %>%
  mutate(cumSurv = prod(1 - pdeath[1:3]),
         cured = sum(tumor_mass == 0, na.rm = T) > 0) %>%
  group_by(mod, scenario, month) %>%
  summarise(mean_cumSurv = mean(cumSurv, na.rm = T),
            prop_cured = mean(cured, na.rm = T))

dat_summ <- dat_long_summ

cumSurvTab2 <- dat_long_summ %>%
  group_by(mod) %>%
  summarise(mean_cumSurv = mean(mean_cumSurv) %>% round(3)) %>%
  rename(`Mean cumulative probability of survival to end of study` = mean_cumSurv)  %>% arrange(-row_number())

bind_cols(cumSurvTab, cumSurvTab2)
latex(cumSurvTab, rowname = NULL, file = "")
```

```{r, eval = F}
getImps <- function(nums) {
  if {classQ$mod_list[[nums]]$finalmodel == "earth"} {
    evimp
  }
  varImp(Q$mod_list[[nums]])$importance %>%
    rownames_to_column("X") %>% 
    mutate(month = nums - 1) %>% 
    rename(importance = Overall) %>% 
    filter(importance > 0)
}

Q <- Q_list$MARS


Q$mod_list[[1]]$finalModel %>% plotmo()
mod <- Q$mod_list[[2]]$finalModel
mod %>% summary()
ev <- evimp(mod)
tibble(
  rownames(ev),
  
)

imps <- map_df(1:6, ~ getImps(.))

ggplot(imps, aes(x = as.factor(month), y = importance, fill = X)) +
  geom_bar(stat = "identity", position = "dodge")

varImp(Q$mod_list[[5]]$finalModel, useModel = T)

varImp(Q$mod_list[[1]])$importance
```

