---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
```

```{r}
int <- F
noise <- F
noise_pred <- F
```

`r ifelse (noise & !noise_pred, "No predicitive noise", "Predictive noise")`

```{r setup}
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, rms, caret, gridExtra, stringr)
source("sim.R")
source("q-functs.R")
source("sim-test.R")
source("results-functs.R")
```

```{r sim}
set.seed(20161116)
dat_long <- sim(int = int, noise = noise, noise_pred = noise_pred, Ttot = 6)
```

```{r formula}
if (int & !noise) {
  nms <- dat_long %>%
    select(tumor_mass, toxicity, dose, Qhat, starts_with("X")) %>% names()
} else if (noise & !int) {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat,
                        starts_with("Z"),
                        starts_with("V")) %>% names()
} else if (noise & int) {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat,
                             starts_with("X"),
                             starts_with("Z"),
                             starts_with("V")) %>% names()
} else {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat) %>% names()
}
response <- "Qhat"
treatment <- "dose"
pred_nms <- nms[!(nms %in% c(response, treatment))]
form <- paste(response,
                   "~",
                   paste0(c(pred_nms, treatment), collapse = " + ")) %>% as.formula()
```

# MARS
```{r}
#--- predictors in PREDICTORS are allowed to interact with predictors in PARENTS
#--- but no other interactions are allowed

PREDICTORS <- pred_nms
PARENTS <-  c("dose")
allowFunct <- function(degree, pred, parents, namesx) {
  if (degree <= 1)
    return(TRUE)
  predictor <- namesx[pred]
  parents <- namesx[parents != 0]
  if ((any(predictor %in% PREDICTORS) &&
       any(parents %in% PARENTS)) ||
      (any(predictor %in% PARENTS) &&
       any(parents %in% PREDICTORS))) {
    return(TRUE)
  }
  FALSE
}

set.seed(20170128)
Q_mars <- Qlearn(
  data = dat_long,
  form = form,
  method = 'gcvEarth',
  trControl = trainControl(method = "none"),
  nk = 200,
  allowed = allowFunct,
  tuneGrid = expand.grid(degree = 2)
)
Q <- Q_mars
```

```{r}
maxPlots(Q, ex_ID, int = int, noise_pred = noise_pred, mon = 5)
```

```{r}
Q_list <- list(MARS = Q_mars)
set.seed(20170128)
dat_test <- sim_test(Q = Q_list, int = int, noise = noise, noise_pred = noise_pred) 
dat_test %>% plots_tab(Q_list = Q_list)
```