---
title: 'Testbed: `r ifelse(params$noise & params$int, "Interaction and noise", ifelse(params$noise, "Noise", ifelse(params$int, "Interaction", "Original")))`'
output: html_notebook
params:
  noise: !r F
  noise_pred: !r F
  int: !r F
---

`r ifelse(params$int, "Interaction = half of people more sensitive to drug (toxicity increases 50% higher than usual with dose), half of people's tumor's reduce 50% more with dose", "Original")`

```{r, eval=FALSE, include=FALSE}
rm(list = ls())
```

```{r}
int <- params$int
noise <- params$noise
noise_pred <- params$noise_pred
```

`r ifelse (noise & !noise_pred, "No predicitive noise", "Predictive noise")`

```{r setup}
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, rms, caret, gridExtra, stringr)
```

```{r sim-functs}
updateW <- function(M, W, D, a1 = 0.1, b1 = 1.2, c1, d1 = 0.5, truth) {
  truth <- rep(truth, length(M))
  W_next <-
    a1 * M + b1 * (c1 * D  - d1) + W +
    ifelse(!truth, rnorm(length(M), 0, 0.05), 0)
  ifelse(W_next > 0, W_next, 0)
}

Wnext <- function(dat, truth = F) {
  if (truth) {
    dat %>% mutate(W_next = updateW(tumor_mass, toxicity, dose,
                                    c1 = c1,
                                    truth = truth))
  } else {
    dat %>%
      mutate(W_next = ifelse(!dead,
                             updateW(tumor_mass, toxicity, dose,
                                     c1 = c1,
                                     truth = truth),
                             NA))
  }
}

updateM <- function(M, W, D, a2 = 0.15, b2 = 1.2, c2, d2 = 0.5,
                    X = 0, Z = 0, a3 = 1e-3, truth) {
  truth <- rep(truth, length(M))
  M_next <- ifelse(M > 0,
                   (a2 * W - b2 * (c2 * D  - d2)) +
                     M + sum(a3 * Z) +
                     ifelse(!truth, rnorm(length(M), 0, 0.05), 0),
                   0)
  ifelse(M_next > 0, M_next, 0)
}

Mnext <- function(dat, truth = F) {
  if (truth) {
    dat %>% mutate(M_next = updateM(tumor_mass, toxicity, dose, 
                                    c2 = c2, truth = truth))
  } else {
    dat %>% mutate(M_next = ifelse(!dead,
                                   updateM(tumor_mass, toxicity, dose, 
                                           c2 = c2, truth = truth),
                                   NA))
  }
}

genIntNoise <- function(dat, int, noise, noise_pred) {
  if (int) {
    dat <- dat %>%
      mutate(
        X1 = runif(nrow(.), min = 0, max = 1),
        X2 = runif(nrow(.), min = 0, max = 1),
        c1 = ifelse(X1 > 0.5, 1.5, 1),
        c2 = ifelse(X2 > 0.5, 1.5, 1)
      )
  } else {
    dat <- dat %>% mutate(c1 = 1, c2 = 1)
  }
  if (noise) {
    dat <- dat %>%
      mutate(
        Z1  = rnorm(nrow(.), mean = 1),
        Z2  = rnorm(nrow(.), mean = 1),
        Z3  = rnorm(nrow(.), mean = 1),
        Z4  = rnorm(nrow(.), mean = 1),
        Z5  = rnorm(nrow(.), mean = 1),
        Z6  = rnorm(nrow(.), mean = -1),
        Z7  = rnorm(nrow(.), mean = -1),
        Z8  = rnorm(nrow(.), mean = -1),
        Z9  = rnorm(nrow(.), mean = -1),
        Z10 = rnorm(nrow(.), mean = -1)
      ) %>% 
      bind_cols(
        replicate(90, rnorm(nrow(.))) %>% as.data.frame())
  } 
  if (noise_pred) {
    dat <- dat %>% mutate(
      noise_chng = Z1 + Z2 + Z3 + Z4 + Z5 + Z6 + Z7 + Z8 + Z9 + Z10)
  } else {
    dat <- dat %>% mutate(noise_chng = 0)
  }
  dat
}

# defined as in NSCLC paper
lambda <- function(M, W, Z, mu0 = -6, mu1 = 1, mu2 = 1.1, mu3 = 0.75,
                   a3 = 0.05) {
  exp(mu0 + mu1 * W + mu2 * M + mu3 * W * M + a3 * Z)
}
```

```{r sim}
simMonth <- function(dat) {
  dat <- Mnext(dat)
  dat <- Wnext(dat)
  dat %>% mutate(
    lam = lambda(M_next, W_next, Z = noise_chng),
    d_next = runif(nrow(.), min = 0, max = 1),
    surv_time = rexp(nrow(.), lam),
    expect_surv_time = 1 / lam,
    dead = ifelse(dead, dead, surv_time < 1)
  )
}

sim <- function(N = 1000, Ttot = 6, int = F, noise = F, noise_pred = F) {
  dat <- tibble(
    ID = 1:N,
    month = rep(0, N),
    tumor_mass = runif(N, min = 0, max = 2),
    toxicity = runif(N, min = 0, max = 2),
    dose = runif(N, min = 0, max = 1),
    dead = rep(F, N)
  )
  
  dat <- genIntNoise(dat, int, noise, noise_pred)
  
  d <- simMonth(dat) %>%
    mutate(reward = ifelse(dead, log(surv_time), 0))
  out <- d
  for (i in 1:(Ttot - 1)) {
    d <- d %>% mutate(month = i,
                      tumor_mass = M_next,
                      toxicity = W_next,
                      dose = d_next) %>%
      simMonth() %>%
      mutate(reward = ifelse(dead, log(i + 1 + surv_time), 0))
    out <- bind_rows(out, d)
  }
  out %>% mutate(
    reward = ifelse(month == Ttot - 1 & !dead, log(surv_time + Ttot - 1), reward),
    Qhat = reward,
    best = NA
  )
}
```

```{r q-functs}
max_df <- function(dat, model, truth, pred, nested = F) {
  dat <- ungroup(dat)
  if (!pred) {
    deads <- filter(dat, is.na(M_next)) %>% mutate(dose = NA)
    dat <- filter(dat, !is.na(M_next))
  }
  
  if (truth) {
    dat <- dat %>% 
      mutate(dose = map(1:nrow(.), ~ seq(0, 1, by = 0.005))) %>%
      unnest()
    dat <- Mnext(dat, truth = truth)
    dat <- Wnext(dat, truth = truth)
    dat <- dat %>% mutate(
      lam = lambda(M_next, W_next, Z = noise_chng),
      expect_surv_time = 1 / lam,
      preds = log(expect_surv_time)
    )
  } else {
    dat <- dat %>% 
      mutate(dose = map(1:nrow(.), ~ seq(0, 1, by = 0.01))) %>%
      unnest() %>%
      mutate(preds = predict(model, .))
  }
  
  if (!nested) {
    dat <- dat %>% group_by(ID) %>% mutate(
      bestR = max(preds),
      best = ifelse(near(preds, bestR), dose, NA),
      best = quantile(best, probs = 0, na.rm = T, type = 3, names = F)
    ) %>% filter(near(dose, best))
    if (!pred) {
      dat <- dat %>% bind_rows(deads) %>% arrange(ID) %>% ungroup() 
    }
  }
  dat %>% ungroup()
}

Qlearn <- function(form, dat_long, boot = F, nstages = 6, ...) {
  mod_list <- list()
  for (i in (nstages - 1):0) {
    dat <- filter(dat_long, month == i)
    mod <- train(form, dat, na.action = na.omit, ...)
    new_dat <- max_df(dat, mod, truth = F, pred = F)
    mod_list[[i + 1]] <- mod
    bestR <- new_dat$bestR
    bestD <- new_dat$best
    if (i > 0) {
      dat_long <- dat_long %>% mutate(
        Qhat = ifelse(month == i - 1,
                      reward + ifelse(!is.na(bestR), bestR, 0),
                      Qhat))
    }
    dat_long <- dat_long %>%
      mutate(best = ifelse(month == i, bestD, best))
  }
  list(
    data = dat_long,
    mod_list = mod_list
  )
}
```

```{r sim-test}
getPreds <- function(Q, name, dat, pred) {
  optimD <- max_df(
    dat = filter(dat, str_detect(group, paste0("^", name, "$"))),
    model = Q$mod_list[[dat$month[1] + 1]],
    truth = F, pred = pred)
  
  bestDopt <- max_df(dat = optimD, model = NULL,
                     truth = T, pred = pred)$dose
  optimD %>% mutate(best_dose = bestDopt)
}

simMonthT <- function(dat, Q, pred) {
  out <- dat %>% filter(group != "best",
                        !str_detect(group, paste(names(Q), collapse = "|"))) %>%
    mutate(dose = ifelse(group == "1on1off",
                         ifelse(dat$month[1] %% 2 == 1, 0, 1),
                         dose))
  
  bestD <- max_df(dat = filter(dat, group == "best"),
                  model = NULL, truth = T, pred = pred)
  
  optimD <- map2_df(Q, names(Q),
                    ~ getPreds(.x, .y, dat = dat, pred = pred))
  
  dat <- bind_rows(out, bestD, optimD) %>% arrange(ID) 
  dat <- Mnext(dat)
  dat <- Wnext(dat)
  dat %>%
    mutate(
      lam = lambda(M_next, W_next, Z = noise_chng),
      pdeath = pexp(lam),
      surv_time = rexp(nrow(.), lam),
      expect_surv_time = 1 / lam,
      dead = ifelse(dead, T, surv_time < 1)
    )
}

sim_test <- function(Q, int, noise, noise_pred, npergroup = 200, Ttot = 6) {
  ngroups <- 12 + length(Q)
  M0 <- runif(npergroup, min = 0, max = 2)
  W0 <- runif(npergroup, min = 0, max = 2)
  
  dat <- tibble(
    ID = 1:npergroup,
    month = rep(0, npergroup),
    tumor_mass = M0,
    toxicity = W0,
    dead = rep(F, npergroup)
  )
  
  dat <- genIntNoise(dat, int, noise, noise_pred)
  
  D1 <- rep(seq(from = 0.1, to = 1, by = 0.1), each = npergroup)
  
  groups <- c(seq(from = 0.1, to = 1, by = 0.1) %>% as.character(),
    "best",
    names(Q), "1on1off")
  
  dat <- dat[rep(seq_len(nrow(dat)), ngroups), ] %>% 
    mutate(
      ID = rep(1:(npergroup * ngroups)),
      group = rep(groups, each = npergroup),
      dose = c(D1, rep(NA, npergroup * (ngroups - 10))),
      best_dose = NA
    )
  
  d <- simMonthT(dat, Q, pred = T) %>%
    mutate(reward = ifelse(dead, log(surv_time), 0))
  out <- d
  for (i in 1:(Ttot - 1)) {
    d <- d %>% mutate(month = i,
                      tumor_mass = M_next,
                      toxicity = W_next) %>%
      simMonthT(Q, pred = F) %>%
      mutate(reward = ifelse(!dead, 0, log(i + 1 + surv_time)))
    out <- bind_rows(out, d)
  }
  out %>% group_by(ID) %>% mutate(
    reward = ifelse(month == Ttot - 1 & !dead, log(surv_time + Ttot - 1), reward),
    pdeath = ifelse(is.na(pdeath), 1, pdeath),
    tot_reward = sum(reward[1:6], na.rm = T),
    Qhat = reward,
    best = NA
  ) %>% arrange(ID) %>% ungroup()
}

```

```{r results-functs}
indPlot <- function(data, ex_ID) {
  tox_mass_plot <- ggplot(data = filter(data, ID == ex_ID)) +
    geom_line(mapping = aes(x = month, y = toxicity, group = ID),
              color = "green") +
    geom_line(mapping = aes(x = month, y = tumor_mass, group = ID))
  
  dose_plot <- ggplot(data = filter(data, ID == ex_ID)) +
    geom_line(mapping = aes(x = month, y = dose, group = ID),
              color = "red") + ylim(0, 1)
  
  list(grid.arrange(tox_mass_plot, dose_plot, nrow = 2, ncol = 1), ex_ID)
}

maxPlots <- function(Q, ex_ID, mon = 5, n = 4, int, noise_pred, seed = 1) {
  dat <- filter(Q$data, month == mon)
  set.seed(seed)
  ids <- dat %>% filter(!is.na(M_next)) %>%
    distinct(ID) %>% sample_n(n) %>% flatten_dbl()
  dat <- dat %>% filter(ID %in% ids)
  
  df <- max_df(
    dat,
    model = Q$mod_list[[mon + 1]],
    truth = F,
    pred = F,
    nested = T
  ) %>% ungroup() %>%
    mutate(ID = factor(ID))
  
  df_best <-
    dat %>% mutate(reward = Qhat) %>% 
    max_df(model = NULL, truth = T, pred = F, nested = T) %>%
    mutate(ID = factor(ID))
  
  ggplot(data = df) +
    geom_line(mapping = aes(x = dose, y = preds, color = ID)) +
    geom_line(
      data = df_best,
      aes(x = dose, y = preds, color = ID),
      linetype = 2
    ) +
    labs(caption = "dotted lines are true values")
}

plots_tab <- function(dat_test_long, Q_list) {
  dat_long_summ <- dat_test_long %>% group_by(ID) %>%
    mutate(
      cumSurv = prod(1 - pdeath[1:6]),
      cured = sum(tumor_mass == 0, na.rm = T) > 0
    ) %>% group_by(group, month) %>% 
    summarise(
      median_dose = median(dose, na.rm = T),
      mean_tox = mean(toxicity, na.rm = T),
      mean_tumor = mean(tumor_mass, na.rm = T),
      median_reward = median(tot_reward, na.rm = T),
      mean_cumSurv = mean(cumSurv, na.rm = T),
      prop_cured = mean(cured, na.rm = T)
    ) %>% mutate(sum_means = mean_tox + mean_tumor)
  
  plot_dose <- ggplot(data = dat_long_summ) +
    geom_line(mapping = aes(
      x = month,
      y = median_dose,
      color = group,
      group = group
    ))
  
  plot_tox <- ggplot(data = dat_long_summ) +
    geom_line(mapping = aes(
      x = month,
      y = mean_tox,
      color = group,
      group = group
    ))
  
  plot_tumor <- ggplot(data = dat_long_summ) +
    geom_line(mapping = aes(
      x = month,
      y = mean_tumor,
      color = group,
      group = group
    ))
  
  plot_sum <- ggplot(data = dat_long_summ) +
    geom_line(mapping = aes(
      x = month,
      y = sum_means,
      color = group,
      group = group
    ))
  
  tab_deaths <- dat_long_summ %>%
    group_by(group) %>%
    summarise(mean_cumSurv = mean(mean_cumSurv)) %>%
    arrange(desc(mean_cumSurv))
  
  tab_cured <- dat_long_summ %>%
    group_by(group) %>%
    summarise(mean_prop_cured = mean(prop_cured)) %>%
    arrange(desc(mean_prop_cured))
  
  tab_reward <- dat_test_long %>%
    group_by(group) %>%
    summarise(median_tot_reward = median(tot_reward, na.rm = T),
              mean_reward = mean(tot_reward)) %>%
    arrange(desc(median_tot_reward))
  
  dat_reward_plot <- dat_test_long %>% ungroup() %>% 
    group_by(group) %>% mutate(mean_reward = mean(tot_reward))
  
  plot_reward <- ggplot(data = dat_reward_plot) +
    geom_boxplot(mapping = aes(
      x = group,
      y = tot_reward,
      color = group
    ), notch = T) +
    geom_point(aes(
      x = group,
      y = mean_reward,
      color = group
    ), shape = 5) +
    labs(y = "log months of survival",
         caption = "diamonds represent mean survival times for each group") + 
    theme(legend.position = "none")
  
  tab_MSE <- dat_test_long %>%
    filter(group %in% names(Q_list)) %>% group_by(group, month) %>% 
    summarise(MSE_dose = mean((dose - best_dose) ^ 2, na.rm = T),
              MAE_dose = mean(abs(dose - best_dose), na.rm = T))
  
  list(
    plot_dose = plot_dose,
    plot_tox = plot_tox,
    plot_tumor = plot_tumor,
    plot_sum = plot_sum,
    plot_reward = plot_reward,
    table_deaths = tab_deaths,
    table_cured = tab_cured,
    table_rewards = tab_reward,
    tab_MSE = tab_MSE
  )
}
```

```{r}
set.seed(20161116)
dat_long <- sim(int = int, noise = noise, noise_pred = noise_pred, Ttot = 6)
```

```{r formula}
if (int & !noise) {
  nms <- dat_long %>%
    select(tumor_mass, toxicity, dose, Qhat, starts_with("X")) %>% names()
} else if (noise & !int) {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat,
                        starts_with("Z"),
                        starts_with("V")) %>% names()
} else if (noise & int) {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat,
                             starts_with("X"),
                             starts_with("Z"),
                             starts_with("V")) %>% names()
} else {
  nms <- dat_long %>% select(tumor_mass, toxicity, dose, Qhat) %>% names()
}
response <- "Qhat"
treatment <- "dose"
pred_nms <- nms[!(nms %in% c(response, treatment))]
form <- paste(response,
                   "~",
                   paste0(c(pred_nms, treatment), collapse = " + ")) %>% as.formula()
```

```{r}
set.seed(20170321)
ex_ID <- sample(dat_long$ID, 1)
indPlot(dat_long, ex_ID)
```

# rpart
```{r}
# grid <- expand.grid(cp = 10^(seq(-4, -3, 1)))
Q_rpart <- Qlearn(
  form = form,
  dat_long,
  # tuneGrid = expand.grid(cp = 10^(seq(-7, -1, 1))),
  # trControl = trainControl(method = "cv"),
  method = 'rpart1SE',
  maxsurrogate = 0,
  minbucket = 5
)
Q <- Q_rpart
```

```{r}
maxPlots(Q, ex_ID, int = int, noise_pred = noise_pred)
```

# MARS
```{r}
#--- predictors in PREDICTORS are allowed to interact with predictors in PARENTS
#--- but no other interactions are allowed

PREDICTORS <- pred_nms
PARENTS <-  c("dose")
allowFunct <- function(degree, pred, parents, namesx) {
  if (degree <= 1)
    return(TRUE)
  predictor <- namesx[pred]
  parents <- namesx[parents != 0]
  if ((any(predictor %in% PREDICTORS) &&
       any(parents %in% PARENTS)) ||
      (any(predictor %in% PARENTS) &&
       any(parents %in% PREDICTORS))) {
    return(TRUE)
  }
  FALSE
}

set.seed(20170128)
Q_mars <- Qlearn(
  form,
  dat_long,
  method = 'gcvEarth',
  trControl = trainControl(method = "none"),
  nk = 200,
  allowed = allowFunct,
  tuneGrid = expand.grid(degree = 2)
)
Q <- Q_mars
```

```{r}
maxPlots(Q, ex_ID, int = int, noise_pred = noise_pred, mon = 5)
```

# rf
```{r}
# grid <- expand.grid(mtry = seq(2, numpreds, length = 5))
grid <- expand.grid(mtry = floor(sqrt(length(pred_nms))))

Q_rf <- Qlearn(
  form,
  dat_long,
  method = 'ranger',
  tuneGrid = grid,
  trControl = trainControl(method = "none"),
  min.node.size = 5,
  importance = "impurity",
  num.trees = 1000,
  always.split.variables = c("dose")
)

Q <- Q_rf
```

```{r}
maxPlots(Q, ex_ID, int = int, noise_pred = noise_pred)
```

```{r}
Q_list <- list(CART = Q_rpart, MARS = Q_mars, RF = Q_rf)
set.seed(20170128)
dat_test <- sim_test(Q = Q_list, int = int, noise = noise, noise_pred = noise_pred)
dat_test %>% plots_tab(Q_list = Q_list)
```