---
title: "CRT extensions"
output: html_notebook
---

# RCS with one noise var
```{r}
set.seed(20161027)
dat <- dat_long %>% mutate(
  noise = runif(7000),
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  best = ifelse(month == 6, NA, 999)
)

Q <- Qlearn(dat,
            Q_hat ~
              noise +
              tumor_mass + dose + toxicity, method = "rcs", "dose")

sim_test(Q) %>% plots_tab()
```


# Use rpart with reward as a factor

```{r}
set.seed(20161027)
dat <- dat_long %>% mutate(
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  Q_hat = ifelse(Q_hat == -65 | Q_hat == -55, -60, Q_hat) %>% factor(),
  best = ifelse(month == 6, NA, 999)
)

Q <- Qlearn(
  dat,
  Q_hat ~
    tumor_mass + dose + toxicity,
  "dose",
  method = "rpart",
  control =
    rpart.control(
      minsplit = 5,
      minbucket = 1,
      cp = 1e-4,
      xval = 20
    )
)
```

```{r xplor-plots}
dat <- align_df(Q) %>% subset_df(5)

mod <- Q$mod_list[[4]]

ggplot(dat) +
  geom_point(aes(x = tumor_mass, y = reward), shape = 5, color = "red") +
  geom_point(aes(
    x = tumor_mass,
    y = predict(mod) %>%
      apply(
        1, function(z) which.max(z) %>% names() %>% as.numeric()
        )
  ), color = "blue", shape = 2)


ggplot(dat) +
  geom_point(aes(x = toxicity, y = reward), shape = 5, color = "red") +
  geom_point(aes(x = toxicity, y = predict(mod) %>%
      apply(
        1, function(z) which.max(z) %>% names() %>% as.numeric()
        )), color = "blue", shape = 2)
```

```{r}
nested_df <- max_df(dat, Q$mod_list[[5]], Q$formula, idvar = "ID", method = "rpart", nested = T)
set.seed(2)
i <- sample(nested_df$ID, 1)
ggplot(filter(nested_df, ID == i), aes(x = dose, y = preds)) +
  geom_point()

set.seed(5)
ggplot(data = filter(nested_df, ID %in% sample(1:1000, 50))) +
  geom_jitter(mapping = aes(x = dose, y = preds, color = factor(ID), alpha  = 0.5), show.legend = F)
```


```{r}
sim_test(Q) %>% plots_tab()
```

# Add noise to rpart  

```{r}
set.seed(20161027)
dat <- dat_long %>% mutate(
  noise = runif(7000),
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  best = ifelse(month == 6, NA, 999)
)

Q <- Qlearn(
  dat,
  Q_hat ~
    noise +
    tumor_mass + dose + toxicity,
  "dose",
  method = "rpart",
  control =
    rpart.control(
      minsplit = 10,
      minbucket = 5,
      cp = 1e-4,
      xval = 20
    )
)
```

```{r}
sim_test(Q) %>% plots_tab()
```


#### other packages:
MDPtoolbox
iqlearn
qLearn

```{r rf, eval = F}
mod_rf <- train(
  Q_hat ~ tumor_mass + toxicity + dose,
  data = month5,
  method = "rf",
  na.action = na.exclude
)
```

