---
title: 'Sandbox'
output: html_document
---

```{r setup}
rm(list = ls())
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, caret, stringr)
```

```{r}
source("sim.R")
source("q-functs.R")
set.seed(20161116)
dat_long <- sim()
```

```{r}
dat_long <- dat_long %>% mutate(
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  best = ifelse(month == 6, NA, 999)
)
```


```{r}
set.seed(20170128)
Q <- Qlearn(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity,
  treatment = "dose",
  mod_type = "caret",
  na.action = na.omit,
  method = "glmnet"
  )
```

```{r}
set.seed(20170128)
sim_test(Q) %>% plots_tab()
```


```{r}
source("sim.R")
source("qlearn-functs.R")
set.seed(20161116)
dat_long <- sim()
dat <- dat_long %>% filter(month == 5) %>% mutate(Q_hat = reward)
```

```{r model-fitting}
preProcValues <- preProcess(dat %>% select(tumor_mass, toxicity, Q_hat), method = c("center", "scale"))
trainTransformed <- predict(preProcValues, dat)

grid <- expand.grid(sigma = 2^(seq(-5, 15, 2)),
                    C = 2^(seq(-15, 3, 2)))

set.seed(20170130)
mod_svr <- train(
  Q_hat ~ tumor_mass + toxicity + dose,
  data = trainTransformed,
  na.action = na.omit,
  method = 'svmRadialSigma',
  tuneGrid = grid
)

mod <- mod_svr
plot(mod)
mod$finalModel
```

```{r one-stage-optim, eval=FALSE, include=FALSE}
x = seq(0, 1, 0.01)
model <- mod
idvar <- "ID"
data <- dat
method = "ert"
form <- makeRCS(Q_hat ~ tumor_mass + toxicity + dose, "dose", method = "ert")

data_long <- data %>% 
  select(matches(idvar),
         one_of(form$covariates)) %>%
  mutate(dose = map(1:nrow(.), ~ x),
         Q_hat = 0) %>% 
  unnest() %>% predict(preProcValues, .) %>% select(-Q_hat)

data_preds <- data_long %>%
  mutate(preds = ifelse(is.na(tumor_mass), 0, predict(model, .))) %>%
  group_by_(idvar) %>%
  mutate(max = max(preds),
         best = ifelse(near(preds, max), dose, NA) %>% min(na.rm = T))
preds <- data_preds %>%
  select(-dose, -preds) %>% unique()
```


```{r model-fitting}
set.seed(20170130)

grid <- expand.grid(degree = 3)

mod_mars <- train(
  Q_hat ~ tumor_mass + toxicity + dose,
  data = dat,
  na.action = na.omit,
  method = 'bagEarthGCV',
  tuneGrid = grid
  )

mod <- mod_mars
plot(mod)
mod$finalModel
```

```{r one-stage-optim, eval=FALSE, include=FALSE}
x = seq(0, 1, 0.01)
model <- mod
idvar <- "ID"
data <- dat
method = "mars"
form <- makeRCS(Q_hat ~ tumor_mass + toxicity + dose, "dose", method = "mars")

data_long <- data %>% 
  select(matches(idvar),
         one_of(form$covariates)) %>%
  mutate(dose = map(1:nrow(.), ~ x),
         Q_hat = 0) %>% 
  unnest() %>% predict(preProcValues, .) %>% select(-Q_hat)

data_preds <- data_long %>%
  mutate(preds = ifelse(is.na(tumor_mass), 0, predict(model, .))) %>%
  group_by_(idvar) %>%
  mutate(max = max(preds),
         best = ifelse(near(preds, max), dose, NA) %>% min(na.rm = T))
preds <- data_preds %>%
  select(-dose, -preds) %>% unique()
```

```{r qlearn, eval=FALSE, include=FALSE}
dat_long <- dat_long %>% mutate(
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  best = ifelse(month == 6, NA, 999)
)

grid <- expand.grid(degree = 3)

set.seed(20170128)
Q <- Q(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity,
  treatment = "dose",
  mod_type = "caret",
  na.action = na.omit,
  method = 'bagEarthGCV',
  tuneGrid = grid
)
```

```{r full-test}
set.seed(20170128)
sim_test(Q) %>% plots_tab()
```

# GAMSEL

```{r gamsel-single-stage, eval=FALSE, include=FALSE}
# subset only to last month, remove people who have died
dat <- dat_long %>% filter(month == 4) %>% select(reward, tumor_mass, toxicity, dose) 
x <- dat %>% na.omit() %>% select(tumor_mass, toxicity, dose) %>% as.matrix()
y <- dat %>% na.omit() %>% select(reward) %>% as.matrix()

mod1 <- gamsel(x, y)
```

```{r gamsel example data, eval=FALSE, include=FALSE}
rm(list = ls())
data = gendata(
  n = 500,
  p = 12,
  k.lin = 3,
  k.nonlin = 3,
  deg = 8,
  sigma = 0.5
)
attach(data)
bases = pseudo.bases(X, degree = 10, df = 6)
# Gaussian gam
gamsel.out = gamsel(X, y, bases = bases)
par(mfrow = c(1, 2), mar = c(5, 4, 3, 1))
summary(gamsel.out)
gamsel.cv = cv.gamsel(X, y, bases = bases)
par(mfrow = c(1, 1))
plot(gamsel.cv)
par(mfrow = c(3, 4))
plot(gamsel.out, newx = X, index = 20)
```


# STIMA

```{r, eval=FALSE, include=FALSE}
# STIMA ---------------------------------------------------------------

rm(list = ls())
library(pacman)
p_load(tidyverse, stima, rpart)

source("./code/sim3.R")
set.seed(20161116)
dat_long <- sim()

# subset only to last month, remove people who have died
dat <- dat_long %>% filter(month == 5) %>%
  select(ID, reward, tumor_mass, toxicity, dose)

mod <- stima(data = dat %>% select(reward, everything(), -ID) %>% na.omit(),
      maxsplit = 10)

round(mod$full, digits=2)

mod$trunk

mod %>% summary()
pmod <- prune(mod)
plot(mod)

predict(mod)

plot(mod)
```


# SVR

```{r}
preProcValues <- preProcess(dat_long %>% select(tumor_mass, toxicity), method = c("center", "scale"))
trainTransformed <- predict(preProcValues, dat_long)

set.seed(20170128)
Q <- Qlearn(
  data = trainTransformed,
  formula = Q_hat ~ tumor_mass + dose + toxicity,
  treatment = "dose",
  mod_type = "caret",
  na.action = na.omit,
  method = 'svmRadialSigma',
  tuneGrid = expand.grid(sigma = 2^(seq(-5, 15, 2)),
                    C = 2^(seq(-15, 3, 2)))
  )
```

```{r}
set.seed(20170128)
sim_test(Q) %>% plots_tab()
```
