---
title: 'Testbed - one interacting variable'
output: html_document
---

```{r setup}
rm(list = ls())
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, caret, gridExtra, stringr)
```

```{r sim}
source("sim-int.R")
source("q-functs.R")
set.seed(20161116)
dat_long <- sim()
dat_long <- dat_long %>% mutate(
  Q_hat = ifelse(month == 6, NA,
                 ifelse(month == 5, reward, 0)),
  best = ifelse(month == 6, NA, 999)
)
```

```{r}
ex_ID <- sample(dat_long$ID, 1)

tox_mass_plot <- ggplot(
  data = filter(dat_long, ID == ex_ID)
) +
  geom_line(
    mapping = aes(x = month, y = toxicity, group = ID), color = "green"
  ) +
  geom_line(
    mapping = aes(x = month, y = tumor_mass, group = ID) 
  )

dose_plot <- ggplot(
  data = filter(dat_long, ID == ex_ID)
) +
  geom_line(
    mapping = aes(x = month, y = dose, group = ID), color = "red"
  ) + ylim(0, 1)

grid.arrange(tox_mass_plot, dose_plot, nrow = 2, ncol = 1)
```


# RCS

```{r}
set.seed(20170128)
Q_rcs <- Qlearn(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity + X,
  treatment = "dose",
  mod_type = "rcs"
  )
Q <- Q_rcs
```


```{r}
dat <- align_df(Q)

ggplot(filter(dat, month == 4)) +
  geom_point(aes(x = tumor_mass, y = reward)) +
  geom_point(aes(x = tumor_mass, y = Q_hat), color = "blue")
```

```{r}
dat <- filter(dat, month == 5)
nested_df <- max_df(dat, Q$mod_list[[4]], Q$formula, mod_type = Q$mod_type, nested = T)

set.seed(8)
i <- sample(nested_df$ID, 1)
ggplot(filter(nested_df, ID == i), aes(x = dose, y = preds)) +
  geom_point()

set.seed(77)
ggplot(data = filter(nested_df, ID %in% sample(1:1000, 50))) +
  geom_line(mapping = aes(x = dose, y = preds, group = ID))
```

```{r}
set.seed(20170128)
sim_test_df(Q) %>% plots_tab()
```

# GLMNET

```{r}
set.seed(20170128)
Q_glmnet <- Qlearn(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity + X + dose * tumor_mass + dose * toxicity + dose * X,
  treatment = "dose",
  mod_type = "caret",
  na.action = na.omit,
  method = "glmnet"
  )
Q <- Q_glmnet
```

```{r}
dat <- align_df(Q)

ggplot(filter(dat_long, month == 5)) +
  geom_point(aes(x = tumor_mass, y = reward), color = "red") +
  geom_point(aes(x = tumor_mass, y = Q_hat), color = "blue", shape = 4, alpha = 0.6)
```

```{r}
dat <- filter(dat, month == 5)
nested_df <- max_df(dat, Q$mod_list[[4]], Q$formula, mod_type = "caret", nested = T)

set.seed(8)
i <- sample(nested_df$ID, 1)
ggplot(filter(nested_df, ID == i), aes(x = dose, y = preds)) +
  geom_point()

set.seed(77)
ggplot(data = filter(nested_df, ID %in% sample(1:1000, 50))) +
  geom_line(mapping = aes(x = dose, y = preds, group = ID, color = X > 0.5))
```


```{r}
set.seed(20170128)
sim_test_df(Q) %>% plots_tab()
```


# ERT

```{r ert-qlearn}
# Tuning parameters:
#   mtry (# Randomly Selected Predictors) - also K ?
#   numRandomCuts (# Random Cuts) - K in CRT paper ?

grid <- expand.grid(mtry = 4,
                    numRandomCuts = 1)

Q_ert <- Qlearn(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity + X,
  treatment = "dose",
  mod_type = "caret",
  method = 'extraTrees',
  na.action = na.omit,
  tuneGrid = grid,
  ntree = 50, # G in CRT paper
  nodesize = 2 # nmin in CRT paper
)
Q <- Q_ert
```

```{r}
dat <- align_df(Q)

ggplot(filter(dat, month == 5)) +
  geom_point(aes(x = tumor_mass, y = reward)) +
  geom_point(aes(x = tumor_mass, y = Q_hat), color = "blue")
```

```{r}
dat <- filter(dat, month == 5)
nested_df <- max_df(dat, Q$mod_list[[4]], Q$formula, mod_type = Q$mod_type, nested = T)

set.seed(8)
i <- sample(nested_df$ID, 1)
ggplot(filter(nested_df, ID == i), aes(x = dose, y = preds)) +
  geom_point()

set.seed(77)
ggplot(data = filter(nested_df, ID %in% sample(1:1000, 50))) +
  geom_line(mapping = aes(x = dose, y = preds, group = ID, color = X > 0.5))
```


```{r}
set.seed(20170128)
sim_test_df(Q) %>% plots_tab()
```


# MARS 

```{r}
set.seed(20170128)
Q_mars <- Qlearn(
  data = dat_long,
  formula = Q_hat ~ tumor_mass + dose + toxicity + X,
  treatment = "dose",
  mod_type = "caret",
  na.action = na.omit,
  method = 'gcvEarth',
  tuneGrid = expand.grid(degree = 3)
  )
Q <- Q_mars
```


```{r}
dat <- align_df(Q)

ggplot(filter(dat, month == 5)) +
  geom_point(aes(x = tumor_mass, y = reward)) +
  geom_point(aes(x = tumor_mass, y = Q_hat), color = "blue")
```

```{r}
dat <- filter(dat, month == 5)
nested_df <- max_df(dat, Q$mod_list[[4]], Q$formula, mod_type = Q$mod_type, nested = T)

set.seed(8)
i <- sample(nested_df$ID, 1)
ggplot(filter(nested_df, ID == i), aes(x = dose, y = preds)) +
  geom_point()

set.seed(77)
ggplot(dat = filter(nested_df, ID %in% sample(1:1000, 50))) +
  geom_line(mapping = aes(x = dose, y = preds, group = ID, color = X > 0.5))
```

```{r}
set.seed(20170128)
sim_test_df(Q) %>% plots_tab()
```
