---
title: 'Testbed: `r ifelse(params$noise & params$int, "Interaction and noise", ifelse(params$noise, "Noise", ifelse(params$int, "Interaction", "Original")))`'
output: html_notebook
params:
  noise: !r F
  noise_pred: !r F
  int: !r F
---

`r ifelse(params$int, "Interaction = half of people more sensitive to drug (toxicity increases 50% higher than usual with dose), half of people's tumor's reduce 50% more with dose", "Original")`

```{r, eval=FALSE, include=FALSE}
rm(list = ls())
```

```{r}
int <- params$int
noise <- params$noise
noise_pred <- params$noise_pred
```

`r ifelse (params$noise_pred, "Predictive noise", "")`

```{r setup}
knitr::opts_chunk$set(warning = F, message = F)
library(pacman)
p_load(tidyverse, rms, caret, rpart, earth, ranger, gridExtra, stringr, grid)
source("sim.R")
source("sim-test-best-deter.R")
source("q-functs.R")
source("results-functs.R")
```

```{r}
samps <- 1
nstages <- 3
```

```{r}
dat_long <- map_df(1:samps, ~ sim(N = 1000,
                                  int = int, noise = noise,
                                  noise_pred = noise_pred, Ttot = nstages,
                                  seed = 20170411 + .x) %>% mutate(samp = .x))
```

```{r formula}
form <- makeForm(dat_long, int = int, noise = noise)
pred_nms <- form$pred_nms
form <- form$form
```

```{r}
set.seed(20170422)
ex_ID <- sample(dat_long$ID, 1)
ex_ID <- 2
indPlot(dat_long, ex_ID)
```

```{r}
  
  dat <- bind_rows(filter(dat_long, ID == ex_ID),
                   filter(dat_long, ID == ex_ID, month == 2) %>%
                     mutate(month = 3, tumor_mass = M_next, toxicity = W_next))
  save(dat, file = "ind_plot_dat.Rdata")
  
  # p1 <- dat %>% rename(`Tumor mass` = tumor_mass, Toxicity = toxicity) %>%
    # gather(var, val, `Tumor mass`, Toxicity) %>%
    
  p2 <- ggplot(dat) +
    geom_line(mapping = aes(x = month, y = tumor_mass)) +
    geom_line(mapping = aes(x = month, y = toxicity), color = "green", linetype = 2) +
    theme_bw() +
    labs(y = "M (solid); W (dashed)") +
    theme(
      # legend.position = "top",
      # legend.title = element_blank(),
      axis.title.x = element_blank() #,
      # axis.title.y = element_blank()
    )
  p3 <- ggplot(dat) +
    geom_step(aes(x = month, y = beta, group = ID), color = "blue") +
    labs(y = expression(beta)) +
    theme_bw() +
    theme(axis.title.x = element_blank())
    
  
  p1 <- ggplot(data = dat) +
    geom_step(mapping = aes(x = month, y = dose, group = ID),
              color = "red") + ylim(0, 1) +
    labs(x = "Month", y = "Dose") + theme_bw() +
    theme(axis.title.x = element_blank())
  
  grid.draw(rbind(ggplotGrob(p1),
                  ggplotGrob(p2),
                  ggplotGrob(p3), size = "first"))
```

# rpart
```{r}
ptm_rpart <- proc.time()
Q_rpart <- map(
  1:samps,
  ~ Qlearn(
    form = form, 
    dat_long = filter(dat_long, samp == .x),
    nstages = nstages,
    method = 'rpart',
    control = rpart.control(cp = 1e-5,
                            maxcompete = 0,
                            maxsurrogate = 0,
                            minbucket = 5))
) %>% set_names(paste0("CART", 1:samps))
(t_rpart <- proc.time() - ptm_rpart)

# varImp(Q_rpart$CART1$mod_list[[1]]$finalModel)
# imps <-  Q_rpart$CART1$mod_list[[1]]$finalModel$variable.importance
# imps[1]/sum(imps)
```

```{r}
maxPlots(Q_rpart$CART1, dat_long, ex_ID, mon = nstages - 1,
         int = int, noise_pred = noise_pred)
```

# MARS
```{r}
#--- predictors in PREDICTORS are allowed to interact with predictors in PARENTS
#--- but no other interactions are allowed

PREDICTORS <- form$pred_nms
PARENTS <-  c("dose")
allowFunct <- function(degree, pred, parents, namesx) {
  if (degree <= 1)
    return(TRUE)
  predictor <- namesx[pred]
  parents <- namesx[parents != 0]
  if ((any(predictor %in% PREDICTORS) &&
       any(parents %in% PARENTS)) ||
      (any(predictor %in% PARENTS) &&
       any(parents %in% PREDICTORS))) {
    return(TRUE)
  }
  FALSE
}

ptm_mars <- proc.time()

set.seed(20170128)
Q_mars <- map(
  1:samps, ~ Qlearn(
    form,
    filter(dat_long, samp == .x),
    nstages = nstages,
    method = 'gcvEarth',
    trControl = trainControl(method = "none"),
    nk = 200,
    allowed = allowFunct,
    tuneGrid = expand.grid(degree = 2)
  )) %>% set_names(paste0("mars", 1:samps))

(t_mars <- proc.time() - ptm_mars)
```

```{r}
maxPlots(Q_mars$mars1, ex_ID, int = int, noise_pred = noise_pred, mon = 5)
```

# bagMARS
```{r}
set.seed(20170128)
Q_bmars <- Qlearn(
  form,
  dat_long,
  method = 'bagEarthGCV',
  trControl = trainControl(method = "none"),
  nk = 200,
  allowed = allowFunct,
  tuneGrid = expand.grid(degree = 2)
)
Q <- Q_bmars
```

```{r}
maxPlots(Q, ex_ID, int = int, noise_pred = noise_pred, mon = 5)
```

# rf
```{r}
# grid <- expand.grid(mtry = floor(seq(length(pred_nms) / 2, length(pred_nms), length = 4)))

ptm_rf <- proc.time()

set.seed(20170128)
Q_rf <- map(1:samps, ~ Qlearn(
  form,
  filter(dat_long, samp == .x),
  method = 'ranger',
  nstages = nstages,
  tuneGrid = expand.grid(mtry = length(pred_nms)),
  trControl = trainControl(method = "none"),
#   tuneGrid = grid,
#   trControl = trainControl(method = "oob"),
  min.node.size = 5,
  importance = "impurity",
  always.split.variables = c("dose"),
  num.trees = 250
)) %>% set_names(paste0("rf", 1:samps))

(t_rf <- proc.time() - ptm_rf)
```

```{r}
maxPlots(Q_rf$rf1, ex_ID, int = int, noise_pred = noise_pred)
```

```{r}
ptm_test <- proc.time()
# Q_list <- c(Q_rpart, Q_mars, Q_bmars, Q_rf)
Q_list <- Q_rpart
dat_test <- sim_test(Q_list, int = int, noise = noise, noise_pred = noise_pred,
                     npergroup = 2000, Ttot = nstages, seed = 20170410,
                     best = F)
(t_test <- proc.time() - ptm_test)
```


```{r, eval = F}
dat_test %>% group_by(ID) %>%
  mutate(tot_reward = sum(reward)) %>%
  group_by(group) %>%
  summarise(tot_reward = mean(exp(tot_reward), na.rm = T)) %>% 
  ggplot() +
  geom_boxplot(aes(x = group, y = tot_reward)) +
  coord_trans(y = "log")
```

```{r}
type_nm <- paste0(
  ifelse(int, "int", ""),
  ifelse(int & noise, "_", ""),
  ifelse(noise, "noise", ""),
  ifelse(noise_pred, "_pred", ""),
  ifelse(!noise_pred & !noise & !int, "orig", "")
)
prefix <- c("dat_test_", "Q_list_")
var_nms <- map_chr(prefix, ~ paste0(.x, type_nm))
for (i in 1:length(var_nms)) {
  assign(var_nms[[i]], list(dat_test, Q_list)[[i]])
}
save(list = var_nms, file = paste0(type_nm, "_3.Rdata"))

rm(list = c(var_nms, "dat_test", "dat_long", "Q_list",
            "Q_mars", "Q_rf", "Q_rpart"))
```
